server:
  port: 8082
spring:
  application:
    name: ekyc-service
  datasource:
    url: jdbc:postgresql://localhost:5432/kycSessionDb
    username: postgres1
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: 'com.pdev.ekyc_service.kafka.events'

feign:
  client:
    config:
      citizen-service:
        url: http://localhost:8081

