server:
  port: 8081
spring:
  application:
    name: citizen-service
  datasource:
    url: jdbc:postgresql://localhost:5433/citizenDb
    username: postgres1
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    com.pdev.citizen_service: DEBUG
    org.springframework.kafka: INFO
