server:
  port: 8084

spring:
  application:
    name: certificate-service

  cloud:
    config:
      enabled: false    # No Config Server in this project — use local application.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/certificateDb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres1}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:39092}
    properties:
      security.protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${SPRING_KAFKA_PROPERTIES_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG:}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
        enable.idempotence: true
        spring.json.add.type.headers: false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: certificate-service-group
      auto-offset-reset: earliest
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.pdev.certificate_service.kafka.events,com.pdev.citizen_service.kafka.events,com.pdev.document_service.kafka.events"
        spring.json.value.default.type: com.pdev.certificate_service.kafka.events.CertificateIssuanceRequestedEvent
#        spring.json.value.default.type: com.pdev.citizen_service.kafka.events.KycCompletedEvent
        spring.json.add.type.headers: false

    listener:
      ack-mode: RECORD
      concurrency: 2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true      # register this service
    fetch-registry: true            # also fetch the registry (for future Feign calls)
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

logging:
  level:
    com.pdev.certificate_service: DEBUG
    org.springframework.kafka: INFO
